-- =====================================================================
-- 道路巡查系統 PostgreSQL Schema（舊版 / HackMD 筆記整理）
--
-- ⚠️ 這份是早期 HackMD 筆記的整理結果，與現行 web_server 的實際結構
--    已經不同（現行表名為小寫單數如 case_patrol，此處為大寫複數）。
--    現行結構請看 postgresql.md，來源是 TypeORM entity 與 migration。
--    保留此檔僅作為舊版設計的歷史紀錄。
--
-- 執行順序：擴展 → 共用觸發器函式 → 基礎表 → 關聯表 → 分區表與 REF 表 → 附屬表
-- =====================================================================

-- ---------------------------------------------------------------------
-- 擴展
-- ---------------------------------------------------------------------
-- 地理空間
CREATE EXTENSION IF NOT EXISTS postgis;

-- pg_trgm (Trigram Index) 加速文字模糊搜尋 (尚未使用)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------------------------------------------------------------------
-- 共用觸發器函式：更新 UPDATED_AT
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- 基礎表
-- =====================================================================

--【ANNOUNCEMENT】: 公告欄表
CREATE TABLE IF NOT EXISTS ANNOUNCEMENT (
    ID SERIAL PRIMARY KEY,
    TYPE VARCHAR(10),
    TITLE VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_announcement_updated_at BEFORE UPDATE ON ANNOUNCEMENT FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【PROJECTS】: 標案表
CREATE TABLE IF NOT EXISTS PROJECTS (
    ID SERIAL PRIMARY KEY,
    PRJ_ID VARCHAR(10) NOT NULL UNIQUE,    -- 標案號
    CASE_CODE VARCHAR(2),                  -- 標案編碼
    PRJ_NAME VARCHAR(50) NOT NULL,         -- 標案簡稱
    STARTDATE DATE NOT NULL,               -- 起始時間
    ENDDATE DATE NOT NULL,                 -- 結束時間
    PRJ_MAIN VARCHAR(50) NOT NULL,         -- 標案全名
    PRJ_SUB VARCHAR(50),                   -- 標案子名稱
    PROPRIETOR VARCHAR(20) NOT NULL,       -- 業主
    PROPRIETOR_LEVEL INT NOT NULL,         -- 業主等級
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_projects_start_end_date ON PROJECTS(STARTDATE, ENDDATE);
CREATE INDEX IF NOT EXISTS idx_projects_updated_at_created_at ON PROJECTS(UPDATED_AT, CREATED_AT);
CREATE INDEX IF NOT EXISTS idx_projects_prj_id ON PROJECTS(PRJ_ID);
CREATE INDEX IF NOT EXISTS idx_projects_updated_at_prj_id ON PROJECTS(UPDATED_AT, PRJ_ID);

CREATE TRIGGER update_projects_updated_at BEFORE UPDATE ON PROJECTS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【COMPANIES】: 公司表
CREATE TABLE IF NOT EXISTS COMPANIES (
    ID SERIAL PRIMARY KEY,
    KEY VARCHAR(5) NOT NULL UNIQUE,          -- 公司編號
    NAME VARCHAR(30) NOT NULL UNIQUE,        -- 公司名稱
    GROUP_LIMIT INT NOT NULL DEFAULT 3,      -- 群組限制數量
    USER_LIMIT INT NOT NULL DEFAULT 5,       -- 使用者限制數量
    DESCRIPTION VARCHAR(50) DEFAULT '',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE, -- 是否啟用
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_companies_name ON COMPANIES(NAME);
CREATE INDEX IF NOT EXISTS idx_companies_isactive ON COMPANIES(IS_ACTIVE);
CREATE TRIGGER update_companies_updated_at BEFORE UPDATE ON COMPANIES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【VEHICLES】: 車輛表
CREATE TABLE IF NOT EXISTS VEHICLES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vehicles_name ON VEHICLES(NAME);
CREATE TRIGGER update_vehicles_updated_at BEFORE UPDATE ON VEHICLES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【AREAS】: 區域表
CREATE TABLE IF NOT EXISTS AREAS (
    ID SERIAL PRIMARY KEY,
    COUNTY VARCHAR(10) NOT NULL,
    DISTRICT VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (COUNTY, DISTRICT)
);

CREATE INDEX IF NOT EXISTS idx_areas_county_district ON AREAS (COUNTY, DISTRICT);
CREATE TRIGGER update_areas_updated_at BEFORE UPDATE ON AREAS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【SYSTEMS】: 系統表
CREATE TABLE IF NOT EXISTS SYSTEMS (
    ID SERIAL PRIMARY KEY,
    KEY VARCHAR(30) NOT NULL UNIQUE,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(30),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_systems_key ON SYSTEMS(KEY);
CREATE TRIGGER update_systems_updated_at BEFORE UPDATE ON SYSTEMS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【DEALERS】: 經銷商表
CREATE TABLE IF NOT EXISTS DEALERS (
    ID SERIAL PRIMARY KEY,
    KEY VARCHAR(20) UNIQUE NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_dealers_updated_at BEFORE UPDATE ON DEALERS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

INSERT INTO DEALERS(KEY, NAME) VALUES
('SRGEO', '日陞空間資訊股份有限公司'),
('PANSHUO', '磐碩營造有限公司')
ON CONFLICT(KEY) DO NOTHING;

--【USERS】: 使用者表
CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    KEY VARCHAR(25) NOT NULL UNIQUE,     -- 唯一編號 (公司代號 + 使用者帳號)
    USER_ID VARCHAR(20),                 -- 使用者帳號
    USER_NAME VARCHAR(30),               -- 使用者名稱
    PASSWORD VARCHAR(255) NOT NULL,      -- 使用者密碼
    COMPANY_ID INT NOT NULL DEFAULT 1,   -- 使用者所屬公司 ID
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE SET DEFAULT
);

CREATE INDEX IF NOT EXISTS idx_users_key ON USERS(KEY);
CREATE INDEX IF NOT EXISTS idx_users_userid ON USERS(USER_ID);
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON USERS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【GROUPS】: 群組表
CREATE TABLE IF NOT EXISTS GROUPS (
    ID SERIAL PRIMARY KEY,
    KEY VARCHAR(30) NOT NULL UNIQUE,     -- 群組鍵名
    NAME VARCHAR(30) NOT NULL,           -- 群組名稱
    DESCRIPTION VARCHAR(50) DEFAULT '',  -- 群組說明
    COMPANY_ID INT NOT NULL,             -- 群組所屬公司 ID
    IS_ACTIVE BOOLEAN DEFAULT TRUE,      -- 是否啟用
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_groups_key ON GROUPS(KEY);
CREATE INDEX IF NOT EXISTS idx_groups_companyid ON GROUPS(COMPANY_ID);
CREATE TRIGGER update_groups_updated_at BEFORE UPDATE ON GROUPS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【MODULES】: 模組表
CREATE TABLE IF NOT EXISTS MODULES (
    ID SERIAL PRIMARY KEY,
    KEY VARCHAR(30) NOT NULL UNIQUE,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(50) DEFAULT '',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_modules_key ON MODULES(KEY);
CREATE TRIGGER update_modules_updated_at BEFORE UPDATE ON MODULES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【FEATURES】: 模組子功能表
CREATE TABLE IF NOT EXISTS FEATURES (
    ID SERIAL PRIMARY KEY,
    MODULE_ID INT NOT NULL,
    KEY VARCHAR(30) NOT NULL UNIQUE,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(50) DEFAULT '',
    PRIORITY INT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MODULE_ID) REFERENCES MODULES(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_features_moduleid ON FEATURES(MODULE_ID);
CREATE INDEX IF NOT EXISTS idx_features_key ON FEATURES(KEY);
CREATE TRIGGER update_features_updated_at BEFORE UPDATE ON FEATURES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【ROAD_MEASUREMENTS】: 縣市道路資料
CREATE TABLE IF NOT EXISTS ROAD_MEASUREMENTS (
    ID SERIAL PRIMARY KEY,
    COUNTY VARCHAR(50) NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    ROADNUM VARCHAR(50),
    ROAD VARCHAR(50) NOT NULL,
    LENGHT VARCHAR(10),      -- 原欄位名即為 LENGHT (拼字錯誤)，程式端已使用，勿改
    WIDTH VARCHAR(10),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_road_measurements_county_road ON ROAD_MEASUREMENTS(COUNTY, ROAD);
CREATE TRIGGER update_road_measurements_updated_at BEFORE UPDATE ON ROAD_MEASUREMENTS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【REPORTS】: 報表 (日, 月)
CREATE TABLE IF NOT EXISTS REPORTS (
    ID SERIAL PRIMARY KEY,
    DATE_INTERVAL DATERANGE NOT NULL,
    TYPE VARCHAR(1) NOT NULL,
    KEY VARCHAR(30) NOT NULL UNIQUE,
    NAME VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    PROGRESS NUMERIC(5, 2) DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reports_type ON REPORTS(TYPE);
CREATE TRIGGER update_reports_updated_at BEFORE UPDATE ON REPORTS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================================
-- 關聯表
-- =====================================================================

--【PROJECTS_COMPANIES】: 公司對標案關聯表 (一對多)
CREATE TABLE IF NOT EXISTS PROJECTS_COMPANIES (
    ID SERIAL PRIMARY KEY,
    PROJECT_ID INT NOT NULL UNIQUE,
    COMPANY_ID INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_projects_companies_project_id ON PROJECTS_COMPANIES(PROJECT_ID);
CREATE INDEX IF NOT EXISTS idx_projects_companies_company_id ON PROJECTS_COMPANIES(COMPANY_ID);
CREATE TRIGGER update_projects_companies_updated_at BEFORE UPDATE ON PROJECTS_COMPANIES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【PROJECTS_VEHICLES】: 標案對車輛關聯表 (一對多)
CREATE TABLE IF NOT EXISTS PROJECTS_VEHICLES (
    ID SERIAL PRIMARY KEY,
    PROJECT_ID INT NOT NULL,
    VEHICLE_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES(ID) ON DELETE CASCADE,
    UNIQUE (PROJECT_ID, VEHICLE_ID)
);

CREATE INDEX IF NOT EXISTS idx_projects_vehicles_project_id ON PROJECTS_VEHICLES(PROJECT_ID);
CREATE INDEX IF NOT EXISTS idx_projects_vehicles_vehicle_id ON PROJECTS_VEHICLES(VEHICLE_ID);
CREATE INDEX IF NOT EXISTS idx_projects_vehicles_is_active ON PROJECTS_VEHICLES(IS_ACTIVE);
CREATE TRIGGER update_projects_vehicles_updated_at BEFORE UPDATE ON PROJECTS_VEHICLES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【PROJECTS_AREAS】: 標案對區域關聯表 (一對多)
CREATE TABLE IF NOT EXISTS PROJECTS_AREAS (
    ID SERIAL PRIMARY KEY,
    PROJECT_ID INT NOT NULL,
    AREA_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (AREA_ID) REFERENCES AREAS(ID) ON DELETE CASCADE,
    UNIQUE (PROJECT_ID, AREA_ID)
);

CREATE INDEX IF NOT EXISTS idx_projects_areas_project_id ON PROJECTS_AREAS(PROJECT_ID);
CREATE INDEX IF NOT EXISTS idx_projects_areas_area_id ON PROJECTS_AREAS(AREA_ID);
CREATE INDEX IF NOT EXISTS idx_projects_areas_is_active ON PROJECTS_AREAS(IS_ACTIVE);
CREATE TRIGGER update_projects_areas_updated_at BEFORE UPDATE ON PROJECTS_AREAS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【PROJECTS_UPLOAD_DEALERS】: 標案對應的上傳經銷商表
CREATE TABLE IF NOT EXISTS PROJECTS_UPLOAD_DEALERS (
    ID SERIAL PRIMARY KEY,
    PROJECT_ID INT NOT NULL,                 -- 標案表 ID
    DEALER_ID INT NOT NULL,                  -- 經銷商表 ID
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE, -- 上傳是否開啟
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (DEALER_ID) REFERENCES DEALERS(ID) ON DELETE CASCADE,
    UNIQUE (PROJECT_ID, DEALER_ID)
);

CREATE INDEX IF NOT EXISTS idx_projects_upload_dealers_project_id ON PROJECTS_UPLOAD_DEALERS(PROJECT_ID);
CREATE INDEX IF NOT EXISTS idx_projects_upload_dealers_dealer_id ON PROJECTS_UPLOAD_DEALERS(DEALER_ID);
CREATE INDEX IF NOT EXISTS idx_projects_upload_dealers_is_active ON PROJECTS_UPLOAD_DEALERS(IS_ACTIVE);
CREATE TRIGGER update_projects_upload_dealers BEFORE UPDATE ON PROJECTS_UPLOAD_DEALERS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【COMPANIES_USERS】: 公司對使用者關聯表
-- 注意: 參照 PERMISSIONS 表，原筆記未包含其定義，需先建立 PERMISSIONS
CREATE TABLE IF NOT EXISTS COMPANIES_USERS (
    ID SERIAL PRIMARY KEY,
    COMPANY_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL DEFAULT 1,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE, -- 帳號是否啟用
    LOGIN_STATUS INT NOT NULL DEFAULT 0,     -- 嘗試登入次數: -1: 鎖定
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE,
    UNIQUE (COMPANY_ID, USER_ID)
);

CREATE INDEX IF NOT EXISTS idx_companies_users_companyid_userid_permissionid ON COMPANIES_USERS (COMPANY_ID, USER_ID, PERMISSION_ID);
CREATE TRIGGER update_companies_users_updated_at BEFORE UPDATE ON COMPANIES_USERS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【SYSTEMS_USERS】: 系統對使用者關聯表
CREATE TABLE IF NOT EXISTS SYSTEMS_USERS (
    ID SERIAL PRIMARY KEY,
    SYSTEM_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SYSTEM_ID) REFERENCES SYSTEMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    UNIQUE (SYSTEM_ID, USER_ID)
);

CREATE INDEX IF NOT EXISTS idx_systems_users_systemid_userid_isactive ON SYSTEMS_USERS(SYSTEM_ID, USER_ID, IS_ACTIVE);
CREATE TRIGGER update_systems_users_updated_at BEFORE UPDATE ON SYSTEMS_USERS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【GROUPS_USERS】: 群組對使用者關聯表
CREATE TABLE IF NOT EXISTS GROUPS_USERS (
    ID SERIAL PRIMARY KEY,
    GROUP_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    UNIQUE (GROUP_ID, USER_ID)
);

CREATE INDEX IF NOT EXISTS idx_groups_users_groupid_userid_isactive ON GROUPS_USERS(GROUP_ID, USER_ID, IS_ACTIVE);
CREATE TRIGGER update_groups_users_updated_at BEFORE UPDATE ON GROUPS_USERS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【COMPANIES_MODULES】: 公司層級模組管理表 (管理公司可以有哪些模組)
CREATE TABLE IF NOT EXISTS COMPANIES_MODULES (
    ID SERIAL PRIMARY KEY,
    COMPANY_ID INT NOT NULL,
    MODULE_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE,
    FOREIGN KEY (MODULE_ID) REFERENCES MODULES(ID) ON DELETE CASCADE,
    UNIQUE (COMPANY_ID, MODULE_ID)
);

CREATE INDEX IF NOT EXISTS idx_companies_modules_cpid_modid_isactive ON COMPANIES_MODULES(COMPANY_ID, MODULE_ID, IS_ACTIVE);
CREATE TRIGGER update_companies_modules_updated_at BEFORE UPDATE ON COMPANIES_MODULES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 觸發器【add_module_to_company】: 新增/更新 MODULES 後, 自動把該模組加給公司 ID = 1
CREATE OR REPLACE FUNCTION add_module_to_company()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO COMPANIES_MODULES (COMPANY_ID, MODULE_ID, IS_ACTIVE)
    VALUES (1, NEW.ID, TRUE);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_add_module_to_company
AFTER INSERT OR UPDATE ON MODULES
FOR EACH ROW
EXECUTE FUNCTION add_module_to_company();

--【COMPANIES_MODULES_FEATURES】: 公司層級模組功能管理表 (管理公司可以有哪些功能)
CREATE TABLE IF NOT EXISTS COMPANIES_MODULES_FEATURES (
    ID SERIAL PRIMARY KEY,
    COMPANY_MODULE_ID INT NOT NULL,
    FEATURE_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMPANY_MODULE_ID) REFERENCES COMPANIES_MODULES(ID) ON DELETE CASCADE,
    FOREIGN KEY (FEATURE_ID) REFERENCES FEATURES(ID) ON DELETE CASCADE,
    UNIQUE (COMPANY_MODULE_ID, FEATURE_ID)
);

CREATE INDEX IF NOT EXISTS idx_companies_modules_features_cpmodid_fteid_isactive ON COMPANIES_MODULES_FEATURES(COMPANY_MODULE_ID, FEATURE_ID, IS_ACTIVE);
CREATE TRIGGER update_companies_modules_features_updated_at BEFORE UPDATE ON COMPANIES_MODULES_FEATURES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 觸發器【add_feature_to_company_module】: 新增 FEATURES 後, 自動加到公司 ID = 1 的對應模組
CREATE OR REPLACE FUNCTION add_feature_to_company_module()
RETURNS TRIGGER AS $$
DECLARE
    company_module_id INT;
BEGIN
    SELECT ID INTO company_module_id
    FROM COMPANIES_MODULES
    WHERE COMPANY_ID = 1 AND MODULE_ID = NEW.MODULE_ID;

    INSERT INTO COMPANIES_MODULES_FEATURES (COMPANY_MODULE_ID, FEATURE_ID, IS_ACTIVE)
    VALUES (company_module_id, NEW.ID, TRUE);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_add_feature_to_company_module
AFTER INSERT ON FEATURES
FOR EACH ROW
EXECUTE FUNCTION add_feature_to_company_module();

--【GROUPS_MODULES】: 群組對模組的關聯表
CREATE TABLE IF NOT EXISTS GROUPS_MODULES (
    ID SERIAL PRIMARY KEY,
    GROUP_ID INT NOT NULL,
    MODULE_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID) ON DELETE CASCADE,
    FOREIGN KEY (MODULE_ID) REFERENCES MODULES(ID) ON DELETE CASCADE,
    UNIQUE (GROUP_ID, MODULE_ID)
);

CREATE INDEX IF NOT EXISTS idx_groups_modules_groupid_moduleid_isactive ON GROUPS_MODULES(GROUP_ID, MODULE_ID, IS_ACTIVE);
CREATE TRIGGER update_groups_modules_updated_at BEFORE UPDATE ON GROUPS_MODULES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【GROUPS_MODULES_FEATURES】: 群組和模組對子功能的關聯表
CREATE TABLE IF NOT EXISTS GROUPS_MODULES_FEATURES (
    ID SERIAL PRIMARY KEY,
    GROUP_MODULE_ID INT NOT NULL,
    FEATURE_ID INT NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GROUP_MODULE_ID) REFERENCES GROUPS_MODULES(ID) ON DELETE CASCADE,
    FOREIGN KEY (FEATURE_ID) REFERENCES FEATURES(ID) ON DELETE CASCADE,
    UNIQUE (GROUP_MODULE_ID, FEATURE_ID)
);

CREATE INDEX IF NOT EXISTS idx_groups_modules_features_id_isactive ON GROUPS_MODULES_FEATURES(GROUP_MODULE_ID, FEATURE_ID, IS_ACTIVE);
CREATE TRIGGER update_groups_modules_features_updated_at BEFORE UPDATE ON GROUPS_MODULES_FEATURES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【COMPANIES_REPORTS】: 公司對報表關聯表
CREATE TABLE IF NOT EXISTS COMPANIES_REPORTS (
    ID SERIAL PRIMARY KEY,
    COMPANY_ID INT NOT NULL,
    REPORT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID) ON DELETE CASCADE,
    FOREIGN KEY (REPORT_ID) REFERENCES REPORTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    UNIQUE (COMPANY_ID, REPORT_ID)
);

CREATE INDEX IF NOT EXISTS idx_companies_reports_companyid_reportid_userid ON COMPANIES_REPORTS(COMPANY_ID, REPORT_ID, USER_ID);

-- =====================================================================
-- 分區表 + REF 中間表 (分區表無法被外鍵參照，改用 REF 表承接外鍵)
-- =====================================================================

--【VEHICLE_TRACK】: 車輛軌跡表
CREATE TABLE IF NOT EXISTS VEHICLE_TRACK (
    ID SERIAL,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRJ_ID VARCHAR(10) NOT NULL,
    CAR VARCHAR(10) NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    LATITUDE DOUBLE PRECISION NOT NULL,
    IS_START VARCHAR(1) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID, DT_RECORD),
    UNIQUE (ID, DT_RECORD)
) PARTITION BY RANGE(DT_RECORD);

-- 2023 年分區
CREATE TABLE vehicle_track_2023_q1 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2023-01-01') TO ('2023-04-01');
CREATE TABLE vehicle_track_2023_q2 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2023-04-01') TO ('2023-07-01');
CREATE TABLE vehicle_track_2023_q3 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2023-07-01') TO ('2023-10-01');
CREATE TABLE vehicle_track_2023_q4 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2023-10-01') TO ('2024-01-01');

-- 2024 年分區
CREATE TABLE vehicle_track_2024_q1 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2024-01-01') TO ('2024-04-01');
CREATE TABLE vehicle_track_2024_q2 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2024-04-01') TO ('2024-07-01');
CREATE TABLE vehicle_track_2024_q3 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2024-07-01') TO ('2024-10-01');
CREATE TABLE vehicle_track_2024_q4 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2024-10-01') TO ('2025-01-01');

-- 2025 年分區
CREATE TABLE vehicle_track_2025_q1 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2025-01-01') TO ('2025-04-01');
CREATE TABLE vehicle_track_2025_q2 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2025-04-01') TO ('2025-07-01');
CREATE TABLE vehicle_track_2025_q3 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2025-07-01') TO ('2025-10-01');
CREATE TABLE vehicle_track_2025_q4 PARTITION OF VEHICLE_TRACK FOR VALUES FROM ('2025-10-01') TO ('2026-01-01');

CREATE INDEX IF NOT EXISTS idx_vehicle_track_dtrecord_prjid_car ON VEHICLE_TRACK(DT_RECORD, PRJ_ID, CAR);

--【VEHICLE_TRACK_REF】: 對【VEHICLE_TRACK】綁外鍵的中間表
CREATE TABLE IF NOT EXISTS VEHICLE_TRACK_REF (
    ID INT PRIMARY KEY,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- 觸發器【update_vehicle_track_ref】: 新增/更新 VEHICLE_TRACK 後, 同步到 VEHICLE_TRACK_REF
CREATE OR REPLACE FUNCTION update_vehicle_track_ref()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO VEHICLE_TRACK_REF (ID, DT_RECORD) VALUES (NEW.ID, NEW.DT_RECORD)
    ON CONFLICT (ID) DO UPDATE SET DT_RECORD = EXCLUDED.DT_RECORD;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_insert_update_vehicle_track
AFTER INSERT OR UPDATE ON VEHICLE_TRACK
FOR EACH ROW
EXECUTE FUNCTION update_vehicle_track_ref();

-- 觸發器【delete_from_vehicle_track_ref】: 刪除 VEHICLE_TRACK 前, 先刪 VEHICLE_TRACK_REF
CREATE OR REPLACE FUNCTION delete_from_vehicle_track_ref()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM VEHICLE_TRACK_REF WHERE ID = OLD.ID;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER before_delete_vehicle_track
BEFORE DELETE ON VEHICLE_TRACK
FOR EACH ROW
EXECUTE FUNCTION delete_from_vehicle_track_ref();

--【UPLOAD_STATUS_VEHICLE_TRACK】: 車巡軌跡上傳狀態表
CREATE TABLE IF NOT EXISTS UPLOAD_STATUS_VEHICLE_TRACK (
    ID SERIAL PRIMARY KEY,
    VEHICLE_TRACK_ID INT UNIQUE NOT NULL,
    UPLOAD_SRGEO INT DEFAULT 0,
    UPLOAD_SRGEO_AT TIMESTAMP,
    FOREIGN KEY (VEHICLE_TRACK_ID) REFERENCES VEHICLE_TRACK_REF (ID) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION insert_upload_status_vehicle_track()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO UPLOAD_STATUS_VEHICLE_TRACK(VEHICLE_TRACK_ID) VALUES (NEW.ID);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_insert_upload_status
AFTER INSERT ON VEHICLE_TRACK
FOR EACH ROW
EXECUTE FUNCTION insert_upload_status_vehicle_track();

-- ---------------------------------------------------------------------

--【CASE_PATROL】: 車巡案件表
CREATE TABLE IF NOT EXISTS CASE_PATROL (
    ID SERIAL,
    CASE_NUM VARCHAR(30) DEFAULT NULL,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CAR VARCHAR(30) NOT NULL,
    PRJ_ID VARCHAR(10) NOT NULL,
    IMG VARCHAR(50) NOT NULL,
    IMG_DETECT VARCHAR(50) NOT NULL,
    CRACKTYPE VARCHAR(30) NOT NULL,
    DEGREE VARCHAR(10) NOT NULL,
    CRACK_ID INT DEFAULT 0,
    LENGTH DOUBLE PRECISION NOT NULL,
    WIDTH DOUBLE PRECISION NOT NULL,
    AREA DOUBLE PRECISION NOT NULL,
    DEPTH DOUBLE PRECISION DEFAULT NULL,
    IMG_MAP_AREA VARCHAR(50) NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    LATITUDE DOUBLE PRECISION NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, DT_RECORD),
    UNIQUE (CASE_NUM, DT_RECORD)
) PARTITION BY RANGE(DT_RECORD);

-- 2023 年分區
CREATE TABLE case_patrol_2023_q1 PARTITION OF CASE_PATROL FOR VALUES FROM ('2023-01-01') TO ('2023-04-01');
CREATE TABLE case_patrol_2023_q2 PARTITION OF CASE_PATROL FOR VALUES FROM ('2023-04-01') TO ('2023-07-01');
CREATE TABLE case_patrol_2023_q3 PARTITION OF CASE_PATROL FOR VALUES FROM ('2023-07-01') TO ('2023-10-01');
CREATE TABLE case_patrol_2023_q4 PARTITION OF CASE_PATROL FOR VALUES FROM ('2023-10-01') TO ('2024-01-01');

-- 2024 年分區
CREATE TABLE case_patrol_2024_q1 PARTITION OF CASE_PATROL FOR VALUES FROM ('2024-01-01') TO ('2024-04-01');
CREATE TABLE case_patrol_2024_q2 PARTITION OF CASE_PATROL FOR VALUES FROM ('2024-04-01') TO ('2024-07-01');
CREATE TABLE case_patrol_2024_q3 PARTITION OF CASE_PATROL FOR VALUES FROM ('2024-07-01') TO ('2024-10-01');
CREATE TABLE case_patrol_2024_q4 PARTITION OF CASE_PATROL FOR VALUES FROM ('2024-10-01') TO ('2025-01-01');

-- 2025 年分區
CREATE TABLE case_patrol_2025_q1 PARTITION OF CASE_PATROL FOR VALUES FROM ('2025-01-01') TO ('2025-04-01');
CREATE TABLE case_patrol_2025_q2 PARTITION OF CASE_PATROL FOR VALUES FROM ('2025-04-01') TO ('2025-07-01');
CREATE TABLE case_patrol_2025_q3 PARTITION OF CASE_PATROL FOR VALUES FROM ('2025-07-01') TO ('2025-10-01');
CREATE TABLE case_patrol_2025_q4 PARTITION OF CASE_PATROL FOR VALUES FROM ('2025-10-01') TO ('2026-01-01');

CREATE INDEX IF NOT EXISTS idx_case_patrol_id ON CASE_PATROL(ID);
CREATE INDEX IF NOT EXISTS idx_case_patrol_imgd_prjid_ctype_drge_crid ON CASE_PATROL(IMG_DETECT, PRJ_ID, CRACKTYPE, DEGREE, CRACK_ID);
CREATE INDEX IF NOT EXISTS idx_case_patrol_dtrecord_casenum ON CASE_PATROL(DT_RECORD, CASE_NUM);
CREATE INDEX IF NOT EXISTS idx_case_patrol_dtrecord_car_prjid ON CASE_PATROL (DT_RECORD, CAR, PRJ_ID);
CREATE INDEX IF NOT EXISTS idx_case_patrol_dtrecord_prjid_car_ctype_drge ON CASE_PATROL(DT_RECORD, PRJ_ID, CAR, CRACKTYPE, DEGREE);
CREATE INDEX IF NOT EXISTS idx_case_patrol_date_img ON CASE_PATROL(DATE(DT_RECORD), IMG);
CREATE INDEX IF NOT EXISTS ids_case_patrol_dtrecord ON CASE_PATROL(DT_RECORD);

CREATE TRIGGER trigger_update_updated_at BEFORE UPDATE ON CASE_PATROL FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 觸發器【check_case_num_unique_case_patrol】: 更新前檢查 CASE_NUM 跨分區唯一
-- (分區表的 UNIQUE 必須包含分區鍵 DT_RECORD, 無法直接對 CASE_NUM 單獨 UNIQUE, 故用觸發器補)
CREATE OR REPLACE FUNCTION check_case_num_unique_case_patrol()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM CASE_PATROL WHERE CASE_NUM = NEW.CASE_NUM AND ID <> NEW.ID) THEN
        RAISE EXCEPTION 'DUPLICATE CASE_NUM: %', NEW.CASE_NUM;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_check_case_num_unique
BEFORE UPDATE ON CASE_PATROL
FOR EACH ROW EXECUTE FUNCTION check_case_num_unique_case_patrol();

--【CASE_PATROL_REF】: 對【CASE_PATROL】綁外鍵的中間表
CREATE TABLE IF NOT EXISTS CASE_PATROL_REF (
    ID INT PRIMARY KEY,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE OR REPLACE FUNCTION insert_case_patrol_ref()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO CASE_PATROL_REF (ID, DT_RECORD) VALUES (NEW.ID, NEW.DT_RECORD)
    ON CONFLICT (ID) DO UPDATE SET DT_RECORD = EXCLUDED.DT_RECORD;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_after_insert_case_patrol_ref
AFTER INSERT OR UPDATE ON CASE_PATROL
FOR EACH ROW
EXECUTE FUNCTION insert_case_patrol_ref();

CREATE OR REPLACE FUNCTION delete_case_patrol_ref()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM CASE_PATROL_REF WHERE ID = OLD.ID;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_before_delete_case_patrol_ref
BEFORE DELETE ON CASE_PATROL
FOR EACH ROW
EXECUTE FUNCTION delete_case_patrol_ref();

--【CASE_PATROL_ADDRESS】: 車巡案件地址表
CREATE TABLE IF NOT EXISTS CASE_PATROL_ADDRESS (
    ID SERIAL PRIMARY KEY,
    CASE_PATROL_ID INT UNIQUE NOT NULL,
    COUNTY VARCHAR(10) NOT NULL,        -- 縣市
    DISTRICT VARCHAR(10) NOT NULL,      -- 行政區 (town)
    CAVLGE VARCHAR(10),                 -- 里 (suburb, neighbourhood)
    ROAD VARCHAR(100),                  -- 道路
    HOUSE_NUMBER VARCHAR(100),          -- 門牌
    ADDRESS VARCHAR(100),               -- 完整地址
    FOREIGN KEY (CASE_PATROL_ID) REFERENCES CASE_PATROL_REF(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_case_patrol_address_casePatrolId ON CASE_PATROL_ADDRESS(CASE_PATROL_ID);
CREATE INDEX IF NOT EXISTS idx_case_patrol_address_road ON CASE_PATROL_ADDRESS(ROAD);
CREATE INDEX IF NOT EXISTS idx_case_patrol_address_distrcit ON CASE_PATROL_ADDRESS(DISTRICT);

--【CASE_PATROL_STATUS】: 車巡案件狀態表
CREATE TABLE IF NOT EXISTS CASE_PATROL_STATUS (
    ID SERIAL PRIMARY KEY,
    CASE_PATROL_ID INT NOT NULL,
    STATUS INT NOT NULL DEFAULT 0,       -- (0:未篩、1:通過、2:待審、3:刪除) => 0、1 才上傳
    EDITED INT NOT NULL DEFAULT 0,       -- 編輯狀態 (0:未編輯、1:已編輯、2:刪除)
    UPD_STATUS_USR INT DEFAULT 1,        -- 二篩狀態修改的使用者
    UPD_STATUS_USR_AT TIMESTAMP,         -- 使用者修改時間 (二篩)
    UPD_STATUS_ADM INT DEFAULT 1,        -- 二篩狀態修改的管理者
    UPD_STATUS_ADM_AT TIMESTAMP,         -- 管理者修改時間 (二篩)
    UPD_EDITED_USR INT DEFAULT 1,        -- 編輯狀態修改的使用者
    UPD_EDITED_USR_AT TIMESTAMP,         -- 使用者修改時間 (編輯)
    NEED_REPAIR INT DEFAULT 0,           -- 需修復狀態 (0:待觀察、1:需修繕、2:不修繕)
    UPD_NEED_REPAIR_USR INT DEFAULT 1,   -- 需修復狀態修改的使用者
    UPD_NEED_REPAIR_USR_AT TIMESTAMP,    -- 修復狀態使用者修改時間
    FOREIGN KEY (CASE_PATROL_ID) REFERENCES CASE_PATROL_REF(ID) ON DELETE CASCADE,
    FOREIGN KEY (UPD_STATUS_USR) REFERENCES USERS(ID),
    FOREIGN KEY (UPD_STATUS_ADM) REFERENCES USERS(ID),
    FOREIGN KEY (UPD_EDITED_USR) REFERENCES USERS(ID)
);

CREATE INDEX IF NOT EXISTS idx_case_patrol_status_case_patrol_id ON CASE_PATROL_STATUS(CASE_PATROL_ID);
CREATE INDEX IF NOT EXISTS idx_case_patrol_status_casePatrolId_status ON CASE_PATROL_STATUS(CASE_PATROL_ID, STATUS);
CREATE INDEX IF NOT EXISTS idx_case_patrol_status_casePatrolId_edited ON CASE_PATROL_STATUS(CASE_PATROL_ID, EDITED);
CREATE INDEX IF NOT EXISTS idx_case_patrol_status_casePatrolId_usr_adm ON CASE_PATROL_STATUS(CASE_PATROL_ID, UPD_STATUS_USR, UPD_STATUS_ADM);
CREATE INDEX IF NOT EXISTS idx_case_patrol_status_casePatrolId_needPepair ON CASE_PATROL_STATUS(CASE_PATROL_ID, NEED_REPAIR);
CREATE INDEX IF NOT EXISTS idx_case_patrol_status_usr_at_usr ON CASE_PATROL_STATUS(UPD_STATUS_USR_AT, UPD_STATUS_USR);

CREATE OR REPLACE FUNCTION insert_case_patrol_status()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO CASE_PATROL_STATUS(CASE_PATROL_ID, STATUS) VALUES (NEW.ID, 0);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_insert_case_patrol_status
AFTER INSERT ON CASE_PATROL
FOR EACH ROW
EXECUTE FUNCTION insert_case_patrol_status();

--【CASE_PATROL_TAIPEI】: 車巡案件客製表 (台北)
CREATE TABLE IF NOT EXISTS CASE_PATROL_TAIPEI (
    ID SERIAL PRIMARY KEY,
    CASE_PATROL_ID INT UNIQUE NOT NULL,
    ROAD_NUM INT,
    ROAD_DIRECT VARCHAR(2),
    CASE_FROM VARCHAR(5),
    MAIN_TYPE VARCHAR(5),
    SUB_TYPE VARCHAR(10),
    REPORTER VARCHAR(10),
    DTYPE_CODE VARCHAR(3),
    MEMO VARCHAR(250),
    FOREIGN KEY (CASE_PATROL_ID) REFERENCES CASE_PATROL_REF(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_case_patrol_taipei_casePatrolId ON CASE_PATROL_TAIPEI(CASE_PATROL_ID);

--【CASE_PATROL_ORIGINAL_REC】: 車巡案件原始數據表 (第一次 UPDATE 前備份原始值)
CREATE TABLE IF NOT EXISTS CASE_PATROL_ORIGINAL_REC (
    ID SERIAL PRIMARY KEY,
    CASE_PATROL_ID INT UNIQUE NOT NULL,
    CASE_NUM VARCHAR(30) UNIQUE DEFAULT NULL,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CAR VARCHAR(30) NOT NULL,
    PRJ_ID VARCHAR(10) NOT NULL,
    IMG VARCHAR(50) NOT NULL,
    IMG_DETECT VARCHAR(50) NOT NULL,
    CRACKTYPE VARCHAR(30) NOT NULL,
    DEGREE VARCHAR(10) NOT NULL,
    CRACK_ID INT DEFAULT 0,
    LENGTH DOUBLE PRECISION NOT NULL,
    WIDTH DOUBLE PRECISION NOT NULL,
    AREA DOUBLE PRECISION NOT NULL,
    IMG_MAP_AREA VARCHAR(50) NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    LATITUDE DOUBLE PRECISION NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CASE_PATROL_ID) REFERENCES CASE_PATROL_REF(ID) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION copy_case_patrol_to_original_rec()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM CASE_PATROL_ORIGINAL_REC WHERE CASE_PATROL_ID = OLD.ID) THEN
        -- 已有備份, 只同步 CASE_NUM
        UPDATE CASE_PATROL_ORIGINAL_REC SET CASE_NUM = OLD.CASE_NUM WHERE CASE_PATROL_ID = OLD.ID;
    ELSE
        INSERT INTO CASE_PATROL_ORIGINAL_REC (
            CASE_PATROL_ID, CASE_NUM, DT_RECORD, CAR, PRJ_ID, IMG, IMG_DETECT, CRACKTYPE, DEGREE,
            CRACK_ID, LENGTH, WIDTH, AREA, IMG_MAP_AREA, LONGITUDE, LATITUDE)
        VALUES (
            OLD.ID, OLD.CASE_NUM, OLD.DT_RECORD, OLD.CAR, OLD.PRJ_ID, OLD.IMG, OLD.IMG_DETECT, OLD.CRACKTYPE, OLD.DEGREE,
            OLD.CRACK_ID, OLD.LENGTH, OLD.WIDTH, OLD.AREA, OLD.IMG_MAP_AREA, OLD.LONGITUDE, OLD.LATITUDE
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_copy_before_update
BEFORE UPDATE ON CASE_PATROL
FOR EACH ROW EXECUTE FUNCTION copy_case_patrol_to_original_rec();

--【UPLOAD_STATUS_CASE_PATROL】: 車巡案件上傳狀態表
CREATE TABLE IF NOT EXISTS UPLOAD_STATUS_CASE_PATROL (
    ID SERIAL PRIMARY KEY,
    CASE_PATROL_ID INT UNIQUE NOT NULL,
    UPLOAD_PARNSHUO INT DEFAULT 0,
    UPLOAD_PARNSHUO_AT TIMESTAMP,
    UPLOAD_SRGEO INT DEFAULT 0,
    UPLOAD_SRGEO_AT TIMESTAMP,
    UPLOAD_BKUP INT DEFAULT 0,
    UPLOAD_BKUP_AT TIMESTAMP,
    FOREIGN KEY (CASE_PATROL_ID) REFERENCES CASE_PATROL_REF(ID) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION insert_upload_status_case_patrol()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO UPLOAD_STATUS_CASE_PATROL(CASE_PATROL_ID) VALUES (NEW.ID);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_insert_upload_status
AFTER INSERT ON CASE_PATROL
FOR EACH ROW
EXECUTE FUNCTION insert_upload_status_case_patrol();

-- =====================================================================
-- 臺北磐碩 APP
-- =====================================================================

--【USERS_TAIPEI_APP】: 臺北磐碩 APP 使用者表
CREATE TABLE IF NOT EXISTS USERS_TAIPEI_APP (
    ID SERIAL,
    USER_ID VARCHAR(20) PRIMARY KEY,
    USER_NAME VARCHAR(30),
    PASSWORD VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_taipei_app_userId ON USERS_TAIPEI_APP(USER_ID);
CREATE TRIGGER update_users_taipei_app_updated_at BEFORE UPDATE ON USERS_TAIPEI_APP FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【PROJECTS_TAIPEI_APP】: 臺北磐碩 APP 標案表
CREATE TABLE IF NOT EXISTS PROJECTS_TAIPEI_APP (
    ID SERIAL PRIMARY KEY,
    PRJ_ID VARCHAR(2) NOT NULL,
    DISTRICT VARCHAR(5) NOT NULL,
    UNIQUE (PRJ_ID, DISTRICT)
);

--【CASE_TAIPEI_APP】: 臺北磐碩 APP 案件表
CREATE TABLE IF NOT EXISTS CASE_TAIPEI_APP (
    ID SERIAL PRIMARY KEY,
    CASE_NUM VARCHAR(30) UNIQUE DEFAULT NULL,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    IS_OBSERVE VARCHAR(1) NOT NULL,
    PRJ_ID VARCHAR(10) NOT NULL,
    PRJ_CODE_NUM VARCHAR(30) NOT NULL,
    ACCOUNT VARCHAR(10) NOT NULL,
    DISTRICT VARCHAR(10) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    TYPE VARCHAR(1) NOT NULL,
    DIRECTION VARCHAR(1) NOT NULL,
    ROAD_NUM VARCHAR(1) NOT NULL,
    DTYPE VARCHAR(3) NOT NULL,
    DEGREE INT NOT NULL,
    MEMO VARCHAR(250),
    LONGITUDE DOUBLE PRECISION NOT NULL,
    LATITUDE DOUBLE PRECISION NOT NULL,
    IMG VARCHAR(100),
    IMG_BEFOREFAR VARCHAR(100),
    IMG_BEFORECLOSE VARCHAR(100),
    IMG_DURING VARCHAR(100),
    IMG_AFTER VARCHAR(100),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_case_taipei_app_dtRecord ON CASE_TAIPEI_APP(DT_RECORD);
CREATE TRIGGER update_case_taipei_app_updated_at BEFORE UPDATE ON CASE_TAIPEI_APP FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

--【UPLOAD_STATUS_TAIPEI_APP】: 臺北磐碩 APP 上傳狀態表
CREATE TABLE IF NOT EXISTS UPLOAD_STATUS_TAIPEI_APP (
    ID SERIAL PRIMARY KEY,
    CASE_TAIPEI_APP_ID INT UNIQUE NOT NULL,
    UPLOAD_PARNSHUO INT DEFAULT 0,
    UPLOAD_PARNSHUO_AT TIMESTAMP,
    UPLOAD_BKUP INT DEFAULT 0,
    UPLOAD_BKUP_AT TIMESTAMP,
    UPLOAD_SHENGDONG INT DEFAULT 0,
    UPLOAD_SHENGDONG_AT TIMESTAMP,
    FOREIGN KEY (CASE_TAIPEI_APP_ID) REFERENCES CASE_TAIPEI_APP(ID)
);

CREATE OR REPLACE FUNCTION insert_upload_status_taipei_app()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO UPLOAD_STATUS_TAIPEI_APP(CASE_TAIPEI_APP_ID) VALUES (NEW.ID);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_insert_upload_status_taipei_app
AFTER INSERT ON CASE_TAIPEI_APP
FOR EACH ROW
EXECUTE FUNCTION insert_upload_status_taipei_app();

CREATE OR REPLACE FUNCTION check_case_num_unique_case_taipei_app()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM CASE_TAIPEI_APP WHERE CASE_NUM = NEW.CASE_NUM AND ID <> NEW.ID) THEN
        RAISE EXCEPTION 'DUPLICATE CASE_NUM: %', NEW.CASE_NUM;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_check_case_num_unique_case_taipei_app
BEFORE INSERT OR UPDATE ON CASE_TAIPEI_APP
FOR EACH ROW EXECUTE FUNCTION check_case_num_unique_case_taipei_app();

-- =====================================================================
-- 鋪面調查
-- =====================================================================

--【CASE_SURVEY_ORDER】: 鋪面調查收件表
CREATE TABLE IF NOT EXISTS CASE_SURVEY_ORDER (
    ID SERIAL PRIMARY KEY,
    ORDER_NUMBER VARCHAR(15) UNIQUE NOT NULL,
    RECIPIENT VARCHAR(20) NOT NULL,
    SURVEY_DATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_case_survey_order_updated_at BEFORE UPDATE ON CASE_SURVEY_ORDER FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE INDEX IF NOT EXISTS idx_case_survey_order_order_number ON CASE_SURVEY_ORDER(ORDER_NUMBER);
CREATE INDEX IF NOT EXISTS idx_case_survey_order_date_number ON CASE_SURVEY_ORDER (SURVEY_DATE, ORDER_NUMBER);
CREATE INDEX IF NOT EXISTS idx_case_survey_order_active ON CASE_SURVEY_ORDER(IS_ACTIVE);

--【CASE_SURVEY_ORDER_DETAIL】: 鋪面調查收件表 - 細部資訊
CREATE TABLE IF NOT EXISTS CASE_SURVEY_ORDER_DETAIL (
    ID SERIAL PRIMARY KEY,
    CASE_SURVEY_ORDER_ID INT NOT NULL,
    ROAD_NAME VARCHAR(20) NOT NULL,                     -- 道路名稱
    ROAD_START VARCHAR(30) NOT NULL,                    -- 道路起點
    ROAD_END VARCHAR(30) NOT NULL,                      -- 道路迄點
    SAMPLE_COUNT INT NOT NULL CHECK(SAMPLE_COUNT >= 0), -- 樣本數量
    DIRECTION VARCHAR(2) NOT NULL,                      -- 車道方向
    LANE INT NOT NULL,                                  -- 車道
    ROAD_STATION_K VARCHAR(3),                          -- 起點樁號 K
    ROAD_STATION_M VARCHAR(3),                          -- 起點樁號 M
    FOREIGN KEY(CASE_SURVEY_ORDER_ID) REFERENCES CASE_SURVEY_ORDER(ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_case_survey_order_detail_order_id ON CASE_SURVEY_ORDER_DETAIL(CASE_SURVEY_ORDER_ID);

--【CASE_SURVEY_REPORT】: 鋪面調查報表
CREATE TABLE IF NOT EXISTS CASE_SURVEY_REPORT (
    ID SERIAL PRIMARY KEY,
    CASE_SURVEY_ORDER_DETAIL_ID INT NOT NULL,
    TYPE VARCHAR(1) NOT NULL,
    KEY VARCHAR(30) NOT NULL UNIQUE,
    NAME VARCHAR(100) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    PROGRESS NUMERIC(5, 2) DEFAULT 0,
    IS_LOCKED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CASE_SURVEY_ORDER_DETAIL_ID) REFERENCES CASE_SURVEY_ORDER_DETAIL(ID) ON DELETE CASCADE,
    UNIQUE(CASE_SURVEY_ORDER_DETAIL_ID, TYPE)
);

CREATE TRIGGER update_case_survey_report_updated_at BEFORE UPDATE ON CASE_SURVEY_REPORT FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE INDEX IF NOT EXISTS idx_case_survey_report_detail_id ON CASE_SURVEY_REPORT(CASE_SURVEY_ORDER_DETAIL_ID);
CREATE INDEX IF NOT EXISTS idx_case_survey_report_key ON CASE_SURVEY_REPORT(KEY);

--【CASE_SURVEY】: 鋪面調查案件表
CREATE TABLE IF NOT EXISTS CASE_SURVEY (
    ID SERIAL,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CASE_NUM VARCHAR(18) DEFAULT NULL,
    PRJ_ID VARCHAR(15) NOT NULL,
    SAM_ID INT NOT NULL,
    SURVEY_DATE DATE NOT NULL,
    WEATHER VARCHAR(1) NOT NULL,
    USER_RECORD INT NOT NULL,
    USER_ID1 INT NOT NULL,
    USER_ID2 INT DEFAULT NULL,
    DTYPE VARCHAR(20) NOT NULL,
    DEGREE VARCHAR(1),
    DTYPE_LENGTH REAL,
    DTYPE_WIDTH REAL,
    DTYPE_AREA REAL,
    DTYPE_QTY INT,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    LATITUDE DOUBLE PRECISION NOT NULL,
    REMARK VARCHAR(50),
    IMG VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, DT_RECORD),
    UNIQUE (CASE_NUM, DT_RECORD),
    FOREIGN KEY (USER_RECORD) REFERENCES USERS(ID),
    FOREIGN KEY (USER_ID1) REFERENCES USERS(ID),
    FOREIGN KEY (USER_ID2) REFERENCES USERS(ID)
) PARTITION BY RANGE(DT_RECORD);

-- 2024 年分區
CREATE TABLE case_survey_2024_q1 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2024-01-01') TO ('2024-04-01');
CREATE TABLE case_survey_2024_q2 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2024-04-01') TO ('2024-07-01');
CREATE TABLE case_survey_2024_q3 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2024-07-01') TO ('2024-10-01');
CREATE TABLE case_survey_2024_q4 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2024-10-01') TO ('2025-01-01');

-- 2025 年分區
CREATE TABLE case_survey_2025_q1 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2025-01-01') TO ('2025-04-01');
CREATE TABLE case_survey_2025_q2 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2025-04-01') TO ('2025-07-01');
CREATE TABLE case_survey_2025_q3 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2025-07-01') TO ('2025-10-01');
CREATE TABLE case_survey_2025_q4 PARTITION OF CASE_SURVEY FOR VALUES FROM ('2025-10-01') TO ('2026-01-01');

CREATE INDEX IF NOT EXISTS idx_case_survey_surveydate_userrecord ON CASE_SURVEY(SURVEY_DATE, USER_RECORD);
CREATE INDEX IF NOT EXISTS idx_case_survey_prj_id ON CASE_SURVEY(PRJ_ID);
CREATE INDEX IF NOT EXISTS idx_case_survey_prj_sam ON CASE_SURVEY(PRJ_ID, SAM_ID);

CREATE TRIGGER update_case_survey_updated_at BEFORE UPDATE ON CASE_SURVEY FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE FUNCTION check_case_num_unique_case_survey()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM CASE_SURVEY WHERE CASE_NUM = NEW.CASE_NUM AND ID <> NEW.ID) THEN
        RAISE EXCEPTION 'DUPLICATE CASE_NUM: %', NEW.CASE_NUM;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_before_check_case_num_unique_case_survey
BEFORE INSERT OR UPDATE ON CASE_SURVEY
FOR EACH ROW EXECUTE FUNCTION check_case_num_unique_case_survey();

--【CASE_SURVEY_REF】: 對【CASE_SURVEY】綁外鍵的中間表
CREATE TABLE IF NOT EXISTS CASE_SURVEY_REF (
    ID INT PRIMARY KEY,
    DT_RECORD TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE OR REPLACE FUNCTION insert_case_survey_ref()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO CASE_SURVEY_REF (ID, DT_RECORD) VALUES (NEW.ID, NEW.DT_RECORD)
    ON CONFLICT (ID) DO UPDATE SET DT_RECORD = EXCLUDED.DT_RECORD;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_after_insert_case_survey_ref
AFTER INSERT OR UPDATE ON CASE_SURVEY
FOR EACH ROW
EXECUTE FUNCTION insert_case_survey_ref();

CREATE OR REPLACE FUNCTION delete_case_survey_ref()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM CASE_SURVEY_REF WHERE ID = OLD.ID;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_before_delete_case_survey_ref
BEFORE DELETE ON CASE_SURVEY
FOR EACH ROW
EXECUTE FUNCTION delete_case_survey_ref();

--【CASE_SURVEY_STATUS】: 鋪面調查案件狀態表
CREATE TABLE IF NOT EXISTS CASE_SURVEY_STATUS (
    ID SERIAL PRIMARY KEY,
    CASE_SURVEY_ID INT NOT NULL,
    STATUS INT NOT NULL DEFAULT 0,      -- (0:未檢查, 1:已檢查, 2:刪除)
    UPD_STATUS_USR INT DEFAULT 1,       -- 狀態修改的使用者
    UPD_STATUS_USR_AT TIMESTAMP,        -- 使用者修改時間
    FOREIGN KEY (CASE_SURVEY_ID) REFERENCES CASE_SURVEY_REF(ID) ON DELETE CASCADE,
    FOREIGN KEY (UPD_STATUS_USR) REFERENCES USERS(ID)
);

CREATE OR REPLACE FUNCTION insert_case_survey_status()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO CASE_SURVEY_STATUS(CASE_SURVEY_ID) VALUES (NEW.ID);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_insert_case_survey_status
AFTER INSERT ON CASE_SURVEY
FOR EACH ROW
EXECUTE FUNCTION insert_case_survey_status();

--【CASE_SURVEY_ADDRESS】: 鋪面調查案件地址表
CREATE TABLE IF NOT EXISTS CASE_SURVEY_ADDRESS (
    ID SERIAL PRIMARY KEY,
    CASE_SURVEY_ID INT UNIQUE NOT NULL,
    COUNTY VARCHAR(10) NOT NULL,
    DISTRICT VARCHAR(10) NOT NULL,
    ROAD VARCHAR(30) NOT NULL,
    ROAD_START VARCHAR(30) NOT NULL,
    ROAD_END VARCHAR(30) NOT NULL,
    ROAD_NUM INT NOT NULL,
    ROAD_LENGTH REAL NOT NULL,
    ROAD_WIDTH REAL NOT NULL,
    ROAD_AREA REAL NOT NULL,
    FOREIGN KEY (CASE_SURVEY_ID) REFERENCES CASE_SURVEY_REF(ID) ON DELETE CASCADE
);

--【CASE_SURVEY_HISTORY】: 鋪面調查案件歷程記錄
CREATE TABLE IF NOT EXISTS CASE_SURVEY_HISTORY (
    ID SERIAL PRIMARY KEY,
    CASE_SURVEY_ID INT NOT NULL,
    VERSION INT NOT NULL,                                     -- 版本
    SNAPSHOT_JSON JSONB NOT NULL,                             -- 當時的完整資料快照
    MODIFIED_BY INT NOT NULL,                                 -- 修改人
    MODIFIED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 修改時間
    FOREIGN KEY (CASE_SURVEY_ID) REFERENCES CASE_SURVEY_REF(ID) ON DELETE CASCADE,
    FOREIGN KEY (MODIFIED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IF NOT EXISTS idx_case_survey_history_surveyid ON CASE_SURVEY_HISTORY(CASE_SURVEY_ID);